### ISSUE TITLE
Težave s funkcijo `redirect`

### ISSUE THREAD

**Issue by TomasRode** [matejske/OPB-zavarovalnica#1]
Pozdravljeni,

naleteli smo na težavo, saj se nam funkcija `redirect` ne odziva. Na primeru post zahteveka na povezavi `/sklenitev_kaskoplus` - izvede nam vse ukaze do redirect, vendar se povezava ne izvede. V konzoli nismo opazili nobene napake. Hvaležni bomo pomoči.

Lep pozdrav,

Tomaž Rode

**Comment by jaanos** [comment]
Problem je očitno v tem, da je na obrazcu uporabljen razred `php-email-form`, s čimer uporabljena predloga poskrbi, da se naredi asinhron zahtevek - obrazec se pošlje, odgovor se pa ne prikaže.

Mimogrede, če želite dobiti ID vstavljene vrstice, si lahko pomagate s stavkom `RETURNING`, npr.
```python
        cur.execute("""
            INSERT INTO zavarovanja (komitent_id, datum_police, premija, tip_zavarovanja)
            VALUES (%s, %s, %s, %s)
            RETURNING stevilka_police
        """, ('875-23-989', date.today(), float(vrednost) * 0.05, 2))
        stevilka_police, = cur.fetchone()
```
Svetujem še, da namesto da datum nastavite z `date.today()`, stolpcu `datum_police` nastavite privzeto vrednost na `now()`, pa ga pri dodajanju ne bo potrebno navajati.

Opazil sem še sledeče nevarne poizvedbe:
https://github.com/matejske/OPB-zavarovalnica/blob/215c515b4c4f1ed36d5e25e52fa01fa50ac1b217/zavarovalnica.py#L221
https://github.com/matejske/OPB-zavarovalnica/blob/215c515b4c4f1ed36d5e25e52fa01fa50ac1b217/zavarovalnica.py#L348
https://github.com/matejske/OPB-zavarovalnica/blob/215c515b4c4f1ed36d5e25e52fa01fa50ac1b217/zavarovalnica.py#L394
Če v poizvedbo vstavljate samo en podatek, ga podajte v seznamu ali 1-terici (npr. `(emso, )`) kot drugi argument metode `execute`.

Tukaj manjka še `ROOT`:
https://github.com/matejske/OPB-zavarovalnica/blob/215c515b4c4f1ed36d5e25e52fa01fa50ac1b217/zavarovalnica.py#L381

**Comment by TomasRode** [comment]
Najlepša hvala!
