### ISSUE TITLE
Težava s prikazom tabel

### ISSUE THREAD

**Issue by TomasRode** [matejske/OPB-zavarovalnica#2]
Pozdravljeni,

zopet se nam je pojavila težava. Tokrat nam na straneh, kjer želimo prikazati vse podatke v bazi (npr. `'/agent/0000/avtomobilska'` za EMSO: 0000 in GESLO: tomas), ne prikaže tabel, ponovno pa ne javlja nobene napake. Z umeščanjem ukazov "print" smo prišli do domneve, da nam sploh ne izvede zanke `%for (polica_id,vrsta,avto_id) in avtomobilska:`.  Preseneča nas, ker mislimo, da smo na enak način sprogramirali pregled zavarovanj za zavarovance, ki pa deluje.

Lep pozdrav,
Tomaž Rode

**Comment by matejske** [comment]
Pozdravljeni,

kot opomba k zgornjemu zapisu, smo opazili, da se nam tabela iz baze normalno izpisuje na strani [http://localhost:8080/testi](http://localhost:8080/testi). Na tabeli na tej strani, tudi pravilno deluje iskalnik po tabeli in delitev na podstrani tabele. 

Torej problem, da ne izpisuje določenih tabel nastane šele po prijavi uporabnika. Kot je zapisano zgoraj, pa deluje izpis posameznih zavarovanj za posameznega zavarovanca, npr. na strani [http://localhost:8080/zavarovanec/0000/moja_avtomobilska](http://localhost:8080/zavarovanec/0000/moja_avtomobilska). Kljub izpisovanju, pa na tabelah po prijavi zavarovanca, ne deluje iskalnik in ostale fukncionalnosti.

Hvala za pomoč in lepo pozdravljeni,
Matej Škerlep

**Comment by matejske** [comment]
Pozdravljeni,

težavo z ne-nalaganjem tabel smo ravnokar odpravili, tako da bi vas prosili le še za pomoč pri nedelovanju Javascripta za filtriranje tabel znotraj poslovalnice.

Hvala in lep pozdrav,
Matej Škerlep

**Comment by matejske** [comment]
Sem uspel urediti tudi to težavo, tako da bom zaprl ta issue.
